name: Run BlazeMeter Test

on:
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Secret Exists
        env:
          TEST_ID: ${{ secrets.BLAZEMETER_TEST_ID }}
        run: |
          if [ -z "$TEST_ID" ]; then
            echo "Test ID secret is missing"
            exit 1
          fi
          echo "Test ID secret is configured."
          
      - name: Run BlazeMeter Test
        uses: BlazeRunner-BZR/Github-Action@v8.1
        with:
          apiKey: ${{ secrets.BLAZEMETER_API_KEY }}
          apiSecret: ${{ secrets.BLAZEMETER_API_SECRET }}
          testID: ${{ secrets.BLAZEMETER_TEST_ID }}
          continuePipeline: false
          showTailLog: true
